spring.application.name=servico-auditor-dlq
server.port=8081


spring.datasource.url=jdbc:h2:mem:auditor_dlq;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=${ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${SECRET_KEY}


queue.dlq-name=T02N_MAURILIO_TOMAZELI_COLODA_DLQ.fifo
